export const WISHLIST_CHANGE_REQUEST = "WISHLIST_CHANGE_REQUEST";
export const WISHLIST_CHANGE_SUCCESS = "WISHLIST_CHANGE_SUCCESS";
export const WISHLIST_CHANGE_FAIL = "WISHLIST_CHANGE_FAIL";

export const WISHLIST_LIST_REQUEST = "WISHLIST_LIST_REQUEST";
export const WISHLIST_LIST_SUCCESS = "WISHLIST_LIST_SUCCESS";
export const WISHLIST_LIST_FAIL = "WISHLIST_LIST_FAIL";

export const WISHLIST_STATUS_REQUEST = "WISHLIST_STATUS_REQUEST";
export const WISHLIST_STATUS_SUCCESS = "WISHLIST_STATUS_SUCCESS";
export const WISHLIST_STATUS_FAIL = "WISHLIST_STATUS_FAIL";
